version: "3.8"
services:
  mongodb:
    image: "mongo:4.4"
    volumes:
    - data:/data/db
    restart: unless-stopped
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
volumes:
  data:
  logs:

